defaults: &defaults
  google_analytics_id: nil

development:
  <<: *defaults
  domain: localhost:3000

test:
  <<: *defaults
  domain: test.host

production:
  <<: *defaults
  domain: gneuniversity.org 
  google_analytics_id: nil
